### ISSUE TITLE
Binding reqs with caps

### ISSUE THREAD

**Issue by jsoldani** [di-unipi-socc/management-analyser-ws#1]
The prototype is currently assuming that the given TOSCA YAML files are such that each requirement of each node template indicates 
* the name of the node template satisfying such requirement (through the field `node` of the requirement assignment), and
* the name of the capability satisfying such requirement (through the field `capability` of the requirement assignment).

E.g.,
```
requirements:
    - endpoint:
        node: backend_api
        capability: endp
    - endpoint
        node: utils_api
        capability: endp
```
(with `backend_api` and  `utils_api` both offering a capability named `endp`)

This is needed to permit deriving the binding between reqs & caps, needed to analyse the management of an app with management protocols
